/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.beans.PropertyChangeEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.Size2DSyntax;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modeloBBDD.AccesoUsuariosBBDD;
import modeloBBDD.CochesBBDD;
import modeloBBDD.ConducenBBDD;
import modeloBBDD.UsuariosBBDD;
import modeloVentanas.AccesoUsuarios;
import modeloVentanas.Coches;
import modeloVentanas.Conducen;
import modeloVentanas.Usuarios;

/**
 *
 * @author bcastrof
 */
public final class vPanelCochesDelegacion extends javax.swing.JFrame {

    private Conducen reserva;
    private Coches coche;
    private Usuarios usuario;
    private AccesoUsuarios accesoUser;
    private final Mail mail = new Mail();
    private final UsuariosBBDD usuariosBBDD = new UsuariosBBDD();
    private final AccesoUsuariosBBDD accesoUsuariosBBDD = new AccesoUsuariosBBDD();
    private final CochesBBDD cochesBBDD = new CochesBBDD();
    private final List<Coches> ch = cochesBBDD.listarCoches();
    private final List<Usuarios> usuarios = new ArrayList<>();
    private final List<AccesoUsuarios> accesoUsuar = new ArrayList<>();
    private final ConducenBBDD conducenBBDD = new ConducenBBDD();
    private final  List<Conducen> conducen2 = conducenBBDD.listarReservas2();
    private final List<Conducen> conducen3 = new ArrayList<>();
    private DefaultTableModel jModel;

    public vPanelCochesDelegacion() {
        initComponents();
        login(vAccesoUsuarios.getAcc());
        // this is a big chapuza, but working.
        Date fea = new Date();
        jDateChooser1.setDate(fea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTapellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTcorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTtelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTusuario = new javax.swing.JTextField();
        altaUsuarios = new javax.swing.JButton();
        modificarUsuarios = new javax.swing.JButton();
        borrarUsuarios = new javax.swing.JButton();
        buscarUsuarios = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTusuarios = new javax.swing.JTable();
        jCheckAdmin = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTmarca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTmodelo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTmatricula = new javax.swing.JTextField();
        altaCoches = new javax.swing.JButton();
        modificarCoches = new javax.swing.JButton();
        borrarCoches = new javax.swing.JButton();
        buscarCoches = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTcoches = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, 7);
        cal.set(Calendar.MINUTE, 45);
        Date date = cal.getTime();
        jsinicio = new javax.swing.JSpinner();
        Calendar cal2 = Calendar.getInstance();
        cal2.set(Calendar.HOUR_OF_DAY, 20);
        cal2.set(Calendar.MINUTE, 00);
        Date date2 = cal2.getTime();
        jsfin = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo_gob-iloveimg-resized.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("NOMBRE:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("APELLIDOS:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("CORREO:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("TELEFONO:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("USUARIO:");

        altaUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Save-35 (1).png"))); // NOI18N
        altaUsuarios.setToolTipText("ALTA");
        altaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        altaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaUsuariosActionPerformed(evt);
            }
        });

        modificarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Save as-35 (1).png"))); // NOI18N
        modificarUsuarios.setToolTipText("MODIFICAR");
        modificarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        borrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Trash Can-35.png"))); // NOI18N
        borrarUsuarios.setToolTipText("BORRAR");
        borrarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buscarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Search-35.png"))); // NOI18N
        buscarUsuarios.setToolTipText("BUSCAR");
        buscarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));

        jTusuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        jTusuarios.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "APELLIDOS", "USERWIN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTusuarios);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jCheckAdmin.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jCheckAdmin.setText("AMDIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(5, 5, 5)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(2, 2, 2)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTcorreo)
                            .addComponent(jTnombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTtelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckAdmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addComponent(altaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("USUARIOS", jPanel2);

        jLabel7.setText("MARCA:");

        jLabel8.setText("MODELO:");

        jLabel9.setText("MATRICULA:");

        altaCoches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Save-35 (1).png"))); // NOI18N
        altaCoches.setToolTipText("ALTA");
        altaCoches.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        altaCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaCochesActionPerformed(evt);
            }
        });

        modificarCoches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Save as-35 (1).png"))); // NOI18N
        modificarCoches.setToolTipText("MODIFICAR");
        modificarCoches.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarCochesActionPerformed(evt);
            }
        });

        borrarCoches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Trash Can-35.png"))); // NOI18N
        borrarCoches.setToolTipText("BORRAR");
        borrarCoches.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarCochesActionPerformed(evt);
            }
        });

        buscarCoches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Search-35.png"))); // NOI18N
        buscarCoches.setToolTipText("BUSCAR");
        buscarCoches.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));

        jTcoches.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        jTcoches.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTcoches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MARCA", "MODELO", "MATRICULA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTcoches);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(38, 38, 38))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(22, 22, 22)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTmatricula)
                            .addComponent(jTmodelo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jTmarca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(altaCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificarCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrarCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(altaCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modificarCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrarCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("COCHES", jPanel3);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.removeAllItems();
        for (int i = 0; i < ch.size(); i++) {
            jComboBox1.addItem(ch.get(i).getMarca().concat(" ").concat(ch.get(i).getModelo().concat(" ").concat(ch.get(i).getMatricula())));
        }
        jPanel7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jsinicio.setModel(new SpinnerDateModel(date, null, null, Calendar.HOUR));
        jsinicio.setEditor(new JSpinner.DateEditor(jsinicio, "HH:mm"));
        jPanel7.add(jsinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 87, 95, -1));

        jsfin.setModel(new SpinnerDateModel(date2, null, null, Calendar.HOUR));
        jsfin.setEditor(new JSpinner.DateEditor(jsfin, "HH:mm"));
        jPanel7.add(jsfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 125, 95, -1));
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 163, 95, -1));

        jButton1.setText("AÑADIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 201, 95, -1));

        jDateChooser1.getDateEditor().addPropertyChangeListener(
            (PropertyChangeEvent e) -> {
                if ("date".equals(e.getPropertyName())) {
                    listarviajes2();
                }
            });
            this.add(jDateChooser1);
            jPanel7.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 11, -1, -1));

            jLabel10.setText("HORA SALIDA:");
            jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 90, -1, -1));

            jLabel11.setText("HORA LLEGADA:");
            jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 128, -1, -1));

            jLabel12.setText("MOTIVO:");
            jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 166, -1, -1));

            jButton2.setVisible(false);
            jButton2.setText("jButton2");
            jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 201, -1, -1));

            jTable1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "USUARIO", "COCHE", "SALIDA", "LLEGADA", "MOTIVO"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, true, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            int index = jTable1.getSelectedRow();
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
                }
            });
            jScrollPane3.setViewportView(jTable1);

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jTabbedPane1.addTab("RESERVAS", jPanel4);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTabbedPane1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTabbedPane1)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void altaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaUsuariosActionPerformed

        usuario = new Usuarios(jTnombre.getText(), jTapellidos.getText(), jTcorreo.getText(), Integer.parseInt(jTtelefono.getText()));
        usuarios.add(usuario);
        String pass = usuario.password();
        String tipo;
        if (jCheckAdmin.isSelected() == true) {
            tipo = "admin";
        } else {
            tipo = "user";
        }
        accesoUser = new AccesoUsuarios(jTusuario.getText().toLowerCase(), pass, tipo);
        accesoUsuar.add(accesoUser);
        accesoUser.setUsuario(usuario);
        usuario.setAccesoUsuarios(accesoUser);
        if (usuariosBBDD.insertUsuarios(usuario) == true && accesoUsuariosBBDD.insertUsuarios(accesoUser) == true) {
            //mail.enviarMail(accesoUsuario.getUserWin(), accesoUsuario.getPass(), usuario.getCorreo(), opcion);
            JOptionPane.showMessageDialog(null, "Alta Usuario realizada Correctamente", "Alta", JOptionPane.INFORMATION_MESSAGE);
            limpiarUsuarios();
            if (mail.adjunto(usuario.getCorreo(), usuario.getAccesoUsuarios().getUserWin(), usuario.getAccesoUsuarios().getPass()) == true) {
                JOptionPane.showMessageDialog(null, "Correo enviado correctamente", "Alta", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Correo no enviado", "Alta", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido dar de alta al usuario.\n"
                    + "Revise los datos\n"
                    + "Si el problema persiste hable con el administrador.", "Alta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_altaUsuariosActionPerformed

    private void altaCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaCochesActionPerformed
        coche = new Coches(jTmarca.getText(), jTmodelo.getText(), jTmatricula.getText().toLowerCase());
        if (cochesBBDD.insertCoche(coche) == true) {
            JOptionPane.showMessageDialog(null, "Coche dado de alta correctamente", "Alta", JOptionPane.INFORMATION_MESSAGE);
            limpiarCoches();
        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido dar de alta el coche", "Alta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_altaCochesActionPerformed

    private void modificarCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarCochesActionPerformed
        coche = new Coches(jTmarca.getText(), jTmodelo.getText(), jTmatricula.getText().toLowerCase());
        if (cochesBBDD.updateCoche(coche) == true) {
            JOptionPane.showMessageDialog(null, "Coche modificado correctamente", "Update", JOptionPane.INFORMATION_MESSAGE);
            limpiarCoches();
        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido modificar el coche", "Update", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarCochesActionPerformed

    private void borrarCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarCochesActionPerformed
        if (cochesBBDD.deleteCoche(jTmatricula.getText()) == true) {
            JOptionPane.showMessageDialog(null, "Coche dado de baja correctamente", "Baja", JOptionPane.INFORMATION_MESSAGE);
            limpiarCoches();
        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido eliminar el coche", "Baja", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_borrarCochesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        accesoUser = vAccesoUsuarios.getAcc();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat horaFormat = new SimpleDateFormat("HH:mm");
        int index = jComboBox1.getSelectedIndex();
        coche = ch.get(index);
        String fecha = dateFormat.format(jDateChooser1.getDate());
        reserva = new Conducen(fecha,
                dateFormat.format(jDateChooser1.getDate()).concat(" ").concat(horaFormat.format(jsinicio.getValue()).concat(":00")),
                dateFormat.format(jDateChooser1.getDate()).concat(" ").concat(horaFormat.format(jsfin.getValue()).concat(":00")),
                jTextField1.getText());
        if (conducenBBDD.insertarReserva(accesoUser, coche, reserva) == true) {

            accesoUser.setConducen(reserva);
         
            reserva.setAccesoUsuarios(accesoUser);
            coche.setConducen(reserva);
            reserva.setCoches(coche);
            conducen2.add(reserva);
            System.out.println(accesoUser.getUserWin() + " " + coche.getMatricula() + " " + fecha + " "
                    + dateFormat.format(jDateChooser1.getDate()).concat(" ").concat(horaFormat.format(jsinicio.getValue()).concat(":00")) + " "
                    + dateFormat.format(jDateChooser1.getDate()).concat(" ").concat(horaFormat.format(jsfin.getValue()).concat(":00")) + " "
                    + jTextField1.getText());
            limpiarReservas();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        SimpleDateFormat formatHora = new SimpleDateFormat("HH:mm");

        int index = jTable1.getSelectedRow();
        if (conducen3.get(index).getAccesoUsuarios().getUserWin().equals(vAccesoUsuarios.getAcc().getUserWin())) {
            Calendar ini = Calendar.getInstance();
            int a = Integer.parseInt(conducen3.get(index).getHoraRecogida().substring(11, 13));
            ini.set(Calendar.HOUR_OF_DAY, a);
            int b = Integer.parseInt(conducen3.get(index).getHoraRecogida().substring(14, 16));
            ini.set(Calendar.HOUR_OF_DAY, b);

            String hora = Integer.toString(a).concat(":").concat(Integer.toString(b));
            Date date2;
            try {
                date2 = formatHora.parse(hora);
                jButton2.setVisible(true);
                jsinicio.setValue(date2);
            } catch (ParseException ex) {
                Logger.getLogger(vPanelCochesDelegacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jTable1MouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vPanelCochesDelegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vPanelCochesDelegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vPanelCochesDelegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vPanelCochesDelegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vPanelCochesDelegacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaCoches;
    private javax.swing.JButton altaUsuarios;
    private javax.swing.JButton borrarCoches;
    private javax.swing.JButton borrarUsuarios;
    private javax.swing.JButton buscarCoches;
    private javax.swing.JButton buscarUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckAdmin;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTapellidos;
    private javax.swing.JTable jTcoches;
    private javax.swing.JTextField jTcorreo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTmarca;
    private javax.swing.JTextField jTmatricula;
    private javax.swing.JTextField jTmodelo;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTtelefono;
    private javax.swing.JTextField jTusuario;
    private javax.swing.JTable jTusuarios;
    private javax.swing.JSpinner jsfin;
    private javax.swing.JSpinner jsinicio;
    private javax.swing.JButton modificarCoches;
    private javax.swing.JButton modificarUsuarios;
    // End of variables declaration//GEN-END:variables
    public void login(AccesoUsuarios acc) {
        if (acc.getTipo().equalsIgnoreCase("user")) {
            jTabbedPane1.setEnabledAt(0, false);
            jTabbedPane1.setEnabledAt(1, false);
            jTabbedPane1.setSelectedIndex(2);
        }
    }

    public void limpiarUsuarios() {
        String t = "";
        jTusuario.setText(t);
        jTnombre.setText(t);
        jTapellidos.setText(t);
        jTcorreo.setText(t);
        jTtelefono.setText(t);
        jCheckAdmin.setSelected(false);

    }

    public void limpiarCoches() {
        String t = "";

        jTmarca.setText(t);
        jTmodelo.setText(t);
        jTmatricula.setText(t);
    }

    public void limpiarReservas() {
        Date date = new Date();
        jComboBox1.setSelectedIndex(0);
        //jDateChooser1.setDate(date);
        jTextField1.setText("");
        listarviajes2();
    }

    public void listarviajes2() {
        jModel = (DefaultTableModel) jTable1.getModel();
        DefaultTableCellRenderer Alinear = new DefaultTableCellRenderer();
        Alinear.setHorizontalAlignment(SwingConstants.CENTER);

        if (jTable1.getRowCount() == 0) {

            int i = 0;
            do {
                if (conducen2.get(i).getFechaRecogida().equals(fecha())) {
                    conducen3.add(conducen2.get(i));
                    jModel.insertRow(jModel.getRowCount(), new Object[]{
                        conducen2.get(i).getAccesoUsuarios().getUsuario().getNombre().concat(" ").concat(conducen2.get(i).getAccesoUsuarios().getUsuario().getApellidos()),
                        conducen2.get(i).getCoches().getMarca().concat(" ").concat(conducen2.get(i).getCoches().getModelo()),
                        //(conducen2.get(i).getFechaRecogida()),
                        conducen2.get(i).getHoraRecogida().substring(11, 16),
                        conducen2.get(i).getHoraEntrega().substring(11, 16),
                        conducen2.get(i).getMotivo()
                    });
                }
                i++;
            } while (i < conducen2.size());

        } else {
            if (conducen3.size() > 0) {
                conducen3.clear();
            }
            jModel.setRowCount(0);
            int i = 0;
            do {
                if (conducen2.get(i).getFechaRecogida().equals(fecha())) {
                    conducen3.add(conducen2.get(i));
                }
                i++;
            } while (i < conducen2.size());
            for (int h = 0; h < conducen3.size(); h++) {
                jModel.insertRow(jModel.getRowCount(), new Object[]{
                    conducen3.get(h).getAccesoUsuarios().getUsuario().getNombre(),
                    conducen3.get(h).getCoches().getMarca().concat(" ").concat(conducen3.get(h).getCoches().getModelo()),
                    // conducen2.get(i).getFechaRecogida(),
                    conducen3.get(h).getHoraRecogida().substring(11, 16),
                    conducen3.get(h).getHoraEntrega().substring(11, 16),
                    conducen3.get(h).getMotivo()
                });
            }
        }
        for (int j = 0; j < 5; j++) {

            jTable1.getColumnModel().getColumn(j).setCellRenderer(Alinear);
        }

    }

    public String fecha() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(jDateChooser1.getDate());
        return date;
    }
}
