--tabla usuarios
CREATE PROCEDURE recuperarFunci
(USW VARCHAR(15))
READS SQL DATA DYNAMIC RESULT SETS 1
BEGIN ATOMIC
DECLARE res CURSOR FOR SELECT * FROM USUARIOS WHERE USERWIN = USW;
OPEN res;
END;

CREATE PROCEDURE recuperarFuncionarios
()
READS SQL DATA DYNAMIC RESULT SETS 1
BEGIN ATOMIC
DECLARE res CURSOR FOR SELECT * FROM USUARIOS;
OPEN res;
END;

--tabla accesoUsuarios

CREATE PROCEDURE recuperarUsuario
(USW VARCHAR(15), PAS VARCHAR(25))
READS SQL DATA DYNAMIC RESULT SETS 1
BEGIN ATOMIC
DECLARE res CURSOR FOR SELECT * FROM ACCESOUSER WHERE USERWIN=USW AND PASS=PAS;
OPEN res;
END;

CREATE PROCEDURE recuperar_Usuario
(IN USW VARCHAR(15), IN PAS VARCHAR(15), OUT USWO VARCHAR(15), OUT TIP VARCHAR(7))
READS SQL DATA
BEGIN ATOMIC
SELECT userwin, tipo INTO USWO, TIP FROM ACCESOUSER WHERE USERWIN=USW AND PASS=PAS;
END;