DROP TABLE USUARIOS CASCADE;
DROP TABLE ACCESOUSUARIOS CASCADE;
DROP TABLE IMPRESORAS CASCADE;
DROP TABLE REPUESTOS CASCADE;
DROP TABLE PCS CASCADE;
DROP TABLE CONFIGURACIONSERVIDORES CASCADE;
DROP TABLE FOTOEQUIPAMENTO CASCADE;

CREATE TABLE USUARIOS
(
NOMBRE VARCHAR(50),
APELLIDOS VARCHAR(50),
USUARIOWIN VARCHAR(10) PRIMARY KEY,
XLNET VARCHAR(10) NOT NULL,
CORREO VARCHAR(150) NOT NULL,
PLANTA INTEGER,
TELEFONO INTEGER NOT NULL
);

CREATE TABLE ACCESOUSUARIOS
(
USUARIOWIN VARCHAR(10) PRIMARY KEY,
PASSWORD VARCHAR(30) NOT NULL,
FECHAPASSWORD VARCHAR(30) NOT NULL
);

ALTER TABLE ACCESOUSUARIOS ADD CONSTRAINT ACC_USW_FK FOREIGN KEY (USUARIOWIN) REFERENCES USUARIOS (USUARIOWIN);

CREATE TABLE IMPRESORAS
(
EJIMPRESORA VARCHAR(15) PRIMARY KEY,
MARCA VARCHAR(20),
MODELO VARCHAR(20),
PLANTA INTEGER,
COLOR BOOLEAN,
TIPO VARCHAR(15) CHECK(TIPO IN('LOCAL','SERVIDOR')),
USUARIOWIN VARCHAR(10),
CDREPUESTO VARCHAR(25),
IDFOTO INTEGER
);

ALTER TABLE IMPRESORAS ADD CONSTRAINT IMP_USW_FK FOREIGN KEY (USUARIOWIN) REFERENCES USUARIOS (USUARIOWIN);

CREATE TABLE REPUESTOS
(
CDREPUESTO VARCHAR(25) PRIMARY KEY,
MARCA VARCHAR(20),
COLOR VARCHAR(30),
CANTIDAD INTEGER,
EJIMPRESORA VARCHAR(15)
);

ALTER TABLE IMPRESORAS ADD CONSTRAINT IMP_CDR_FK FOREIGN KEY (CDREPUESTO) REFERENCES REPUESTOS (CDREPUESTO);

ALTER TABLE REPUESTOS ADD CONSTRAINT REP_EJI_FK FOREIGN KEY (EJIMPRESORA) REFERENCES IMPRESORAS(EJIMPRESORA);

CREATE TABLE PCS 
(
EJPC VARCHAR(15) PRIMARY KEY,
MARCA VARCHAR(20),
MODELO VARCHAR(20),
PLANTA INTEGER,
DESCRIPCION VARCHAR(150),
FECHAOBSCELENCIA VARCHAR(30),
RENTING BOOLEAN,
USUARIOWIN VARCHAR(10)
);

ALTER TABLE PCS ADD CONSTRAINT PCS_USW_FK FOREIGN KEY (USUARIOWIN) REFERENCES USUARIOS (USUARIOWIN);

CREATE TABLE CONFIGURACIONSERVIDORES
(
EJIMPRESORA VARCHAR(15) PRIMARY KEY,
IP VARCHAR(20),
GETWAY VARCHAR(20),
MASCARA VARCHAR(20),
DNS1 VARCHAR(20),
DNS2 VARCHAR(20)
);

ALTER TABLE CONFIGURACIONSERVIDORES ADD CONSTRAINT CON_EJI_FK FOREIGN KEY  (EJIMPRESORA) REFERENCES IMPRESORAS (EJIMPRESORA);

CREATE TABLE FOTOEQUIPAMENTO
(
IDFOTO INTEGER IDENTITY PRIMARY KEY,
TIPOEQUIPAMENTO VARCHAR(50),
URL VARCHAR(200)
);

ALTER TABLE IMPRESORAS ADD CONSTRAINT IMP_IDF_FK FOREIGN KEY (IDFOTO) REFERENCES FOTOEQUIPAMENTO (IDFOTO);


create procedure insertarUsuario
(nombre varchar(50), apellidos varchar(50), usuariowin varchar(10),xlnet varchar(10), correo varchar(150), planta integer, telefono integer)
MODIFIES SQL DATA
BEGIN ATOMIC
INSERT INTO USUARIOS VALUES(nombre, apellidos, usuariowin, xlnet,correo,planta,telefono);
end;

CREATE PROCEDURE MODIFICARUSUARIO
(NOM VARCHAR(50), AP VARCHAR(50), US VARCHAR(10),
XL VARCHAR(10), COR VARCHAR(150), PL INTEGER, TLF INTEGER)
MODIFIES SQL DATA
BEGIN ATOMIC
UPDATE USUARIOS
SET NOMBRE=NOM, APELLIDOS=AP, XLNET=XL, CORREO=COR, PLANTA=PL, TELEFONO=TLF
WHERE USUARIOWIN = US;
END;

CREATE PROCEDURE BORRARUSUARIO
(US VARCHAR(10))
MODIFIES SQL DATA
BEGIN ATOMIC
DELETE FROM USUARIOS WHERE USUARIOWIN=US;
END;

CREATE PROCEDURE listarUsuarios()
READS SQL DATA DYNAMIC RESULT SETS 1
BEGIN ATOMIC
DECLARE result CURSOR FOR SELECT * FROM usuarios;
OPEN result;
END;


