/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
//import javax.swing.Timer;
//import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;
import modeloBBDD.UsuariosBBDD;
import modeloBBDD.AccessoUsuariosBBDD;
import modeloVentanas.AccesoUsuarios;
import modeloVentanas.Impresoras;
import modeloVentanas.Usuarios;

/**
 *
 * @author bcastrof
 */
public class Vusuarios extends javax.swing.JFrame {

    //modelo tabla tUsuarios.
    private DefaultTableModel tMusuarios;
    //alta nuevo usuario.
    private Usuarios usuario = new Usuarios();
    //para la modificacion de usuario.
    private Usuarios oldUsuario = new Usuarios();
    //para enviar la informacion al usuario de sus datos de acceso
    private AccesoUsuarios accesoUsuario = new AccesoUsuarios();
    //acceso usuario que se utiliza para insertar los datos en tabla.
    private AccesoUsuarios accesoUsuarioI = new AccesoUsuarios();
    //para la carga de usuarios en la tabla.
    private List<Usuarios> usuarios = new ArrayList<>();
    //para buscar los usuarios por clave una vez cargados
    private final HashMap<String, Usuarios> usuarioMap = new HashMap<>();
    //para la insercion de un nuevo usuario en la tabla usuarios.
    private final UsuariosBBDD usuariosBBDD = new UsuariosBBDD();
    //para la insercion de un nuevo accessoUsuarios en tabla.
    private final AccessoUsuariosBBDD accessoUsuariosBBDD = new AccessoUsuariosBBDD();
    //referencia de busqueda del hashMap.
    private String clave;

    //int tiempoRepeticion = 6000;
    public Vusuarios() {
        initComponents();
        listarUsuarios();
        // timer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tUsuarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtApellidos = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        jtPlanta = new javax.swing.JTextField();
        jtUserwin = new javax.swing.JTextField();
        jtXlnet = new javax.swing.JTextField();
        jtEjpc = new javax.swing.JTextField();
        jtEjImp = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        limpiarFormulario = new javax.swing.JButton();
        altaNueva = new javax.swing.JButton();
        guardarCambios = new javax.swing.JButton();
        borraRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libreta de Contactos");
        setResizable(false);

        jPanelImage.setBackground(new java.awt.Color(255, 255, 255));
        jPanelImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.white));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\pogramacion\\Proyecto_Delgacion\\appDelegacion\\appDelegacion\\imagenes\\logo_gob-iloveimg-resized.jpg")); // NOI18N
        jPanelImage.add(jLabel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.white));

        jScrollPane2.setBorder(null);

        tUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "APELLIDOS", "USUARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tUsuarios.setName("tUsuarios"); // NOI18N
        tUsuarios.setOpaque(false);
        tUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tUsuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.white));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("NOMBRE:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 26, -1, -1));

        jLabel3.setText("APELLIDOS:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 26, -1, -1));

        jLabel4.setText("CORREO:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 104, -1, -1));

        jLabel5.setText("PLANTA:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 65, -1, -1));

        jLabel6.setText("CONTACTO:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 65, -1, -1));

        jLabel7.setText("USUARIO:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 143, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("XLNET:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 143, -1, -1));

        jLabel9.setText("EJPC:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 180, -1, -1));

        jLabel10.setText("EJIMP:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 180, -1, -1));
        jPanel3.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 23, 250, -1));
        jPanel3.add(jtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 23, 250, -1));
        jPanel3.add(jtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 101, 580, -1));
        jPanel3.add(jtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 62, 250, -1));
        jPanel3.add(jtPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 62, 250, -1));
        jPanel3.add(jtUserwin, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 140, 250, -1));
        jPanel3.add(jtXlnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 140, 250, -1));
        jPanel3.add(jtEjpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 177, 250, -1));
        jPanel3.add(jtEjImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 177, 250, -1));

        buscar.setForeground(new java.awt.Color(240, 240, 240));
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Search-35.png"))); // NOI18N
        buscar.setToolTipText("BUSCAR");
        buscar.setBorder(null);
        buscar.setBorderPainted(false);
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.setOpaque(false);
        jPanel3.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        limpiarFormulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Eraser-35.png"))); // NOI18N
        limpiarFormulario.setToolTipText("LIMPIAR FORMULARIO");
        limpiarFormulario.setBorder(null);
        limpiarFormulario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarFormularioActionPerformed(evt);
            }
        });
        jPanel3.add(limpiarFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        altaNueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Save-35 (1).png"))); // NOI18N
        altaNueva.setToolTipText("NUEVA ALTA");
        altaNueva.setBorder(null);
        altaNueva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        altaNueva.setNextFocusableComponent(jtNombre);
        altaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaNuevaActionPerformed(evt);
            }
        });
        jPanel3.add(altaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        guardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Save as-35 (1).png"))); // NOI18N
        guardarCambios.setToolTipText("GURADAR CAMBIOS");
        guardarCambios.setBorder(null);
        guardarCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCambiosActionPerformed(evt);
            }
        });
        jPanel3.add(guardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        borraRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-Trash Can-35.png"))); // NOI18N
        borraRegistro.setToolTipText("BORRAR REGISTRO");
        borraRegistro.setBorder(null);
        borraRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borraRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borraRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(borraRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tUsuariosMouseClicked
        clave = String.valueOf(tMusuarios.getValueAt(tUsuarios.getSelectedRow(), 2));
        jtNombre.setText(usuarioMap.get(clave).getNombre());
        jtApellidos.setText(usuarioMap.get(clave).getApellidos());
        jtCorreo.setText(usuarioMap.get(clave).getCorreo());
        jtPlanta.setText(Integer.toString(usuarioMap.get(clave).getPlanta()));
        jtTelefono.setText(Integer.toString(usuarioMap.get(clave).getTelefono()));
        jtUserwin.setText(usuarioMap.get(clave).getUserwin());
        jtXlnet.setText(usuarioMap.get(clave).getXlnet());
    }//GEN-LAST:event_tUsuariosMouseClicked

    private void limpiarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarFormularioActionPerformed
        limpiar();
    }//GEN-LAST:event_limpiarFormularioActionPerformed

    private void borraRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borraRegistroActionPerformed
        clave = jtUserwin.getText();
        usuariosBBDD.borrarUsuarioBBDD(usuarioMap.get(clave));
        usuarioMap.remove(clave);
        usuarios.remove(usuarioMap.get(clave));
        limpiar();
    }//GEN-LAST:event_borraRegistroActionPerformed

    private void altaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaNuevaActionPerformed
        //saco y formateo la fecha actual
        SimpleDateFormat formato = new SimpleDateFormat("YYYY-dd-MM");
        Date fechaHoy = new Date();
        formato.format(fechaHoy);
        //genero y codifico la clave
        String pass = usuario.password();
        int hashCode = pass.hashCode();
        //creo nuevo usuario
        usuario = new Usuarios(jtNombre.getText(), jtApellidos.getText(),
                jtUserwin.getText(), jtXlnet.getText(), jtCorreo.getText(),
                Integer.parseInt(jtPlanta.getText()), Integer.parseInt(jtTelefono.getText()));
        //añado usuario al array de usuarios
        usuarios.add(usuario);
        //añado usuario al hashmap
        usuarioMap.put(usuario.getUserwin(), usuario);
        //inserto usuario en tabla
        usuariosBBDD.altaUsuarioBBDD(usuario);
        //creo acceso usuario con los datos a enviar al usuario
        accesoUsuario = new AccesoUsuarios(jtUserwin.getText(), pass, formato.format(fechaHoy));
        //creo nuevo acceso al usuario anterior e inserto en tabla
        accesoUsuarioI = new AccesoUsuarios(jtUserwin.getText(), Integer.toString(hashCode), formato.format(fechaHoy));
        //enlazo usuario con acceso usuario
        usuario.setAccesoUsuario(accesoUsuarioI);
        //inserto acceso usuario en tabla
        accessoUsuariosBBDD.altaAccessoUsuariosBBD(accesoUsuarioI);

        System.out.println(hashCode + " " + pass);

        if (jtEjImp.getText().equals("") || jtEjpc.getText().equals("")) {
            /*
            aqui tengo que abrir una ventana que me permita dar de alta las dos
            cosas o que me abra las ventanas correspondientes y asi asociarlas 
            despues con el usuario.
             */
            System.out.println("he llegado aki");
        } else {
            /*aki tengo que hacer una consulta a tabla para rescatar los datos
            y asociarlos con el usuario.
             */
            Impresoras i = new Impresoras();
            i.setEj_impresora("lol");
            usuario.añadirImpresora(i);
            i.añadirUsuario(usuario);
        }

        limpiar();
    }//GEN-LAST:event_altaNuevaActionPerformed

    private void guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosActionPerformed
        clave = String.valueOf(tMusuarios.getValueAt(tUsuarios.getSelectedRow(), 2));
        oldUsuario = usuarioMap.get(clave);
        usuario = new Usuarios(jtNombre.getText(), jtApellidos.getText(),
                jtUserwin.getText(), jtXlnet.getText(), jtCorreo.getText(),
                Integer.parseInt(jtPlanta.getText()), Integer.parseInt(jtTelefono.getText()));

        if (!usuario.equals(oldUsuario)) {
            usuariosBBDD.modificarUsuarioBBDD(usuario);
        } else {
            System.out.println("sin cambios");
        }
        limpiar();
    }//GEN-LAST:event_guardarCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Vusuarios().setVisible(true);
        });
    }

    public void listarUsuarios() {

        tMusuarios = (DefaultTableModel) tUsuarios.getModel();
        usuarios = usuariosBBDD.listarUsuarios();

        usuarios.forEach((us) -> {
            tMusuarios.insertRow(tMusuarios.getRowCount(), new Object[]{
                us.getNombre(), us.getApellidos(), us.getUserwin()
            });
            usuarioMap.put(us.getUserwin(), us);
        });
    }

    public void limpiar() {
        int filas = tMusuarios.getRowCount();
        jtApellidos.setText("");
        jtCorreo.setText("");
        jtEjpc.setText("");
        jtEjImp.setText("");
        jtNombre.setText("");
        jtPlanta.setText("");
        jtTelefono.setText("");
        jtUserwin.setText("");
        jtXlnet.setText("");
        tMusuarios.setRowCount(0);
        listarUsuarios();
    }

    //TODO  No sé si voy a implatar esto. sirve para hacer un refresco auto.
//    Timer timer = new Timer (tiempoRepeticion, new ActionListener () 
//{ 
//    public void actionPerformed(ActionEvent e) 
//    { 
//    tMusuarios.setRowCount(0);
//    listarUsuarios();
//     } 
//}); 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaNueva;
    private javax.swing.JButton borraRegistro;
    private javax.swing.JButton buscar;
    private javax.swing.JButton guardarCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelImage;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtApellidos;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtEjImp;
    private javax.swing.JTextField jtEjpc;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPlanta;
    private javax.swing.JTextField jtTelefono;
    private javax.swing.JTextField jtUserwin;
    private javax.swing.JTextField jtXlnet;
    private javax.swing.JButton limpiarFormulario;
    private javax.swing.JTable tUsuarios;
    // End of variables declaration//GEN-END:variables
}
